src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[UniqueEntity(fields: ['pseudo'], message: 'This pseudo is\'nt available')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = ["ROLE_USER"];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50, unique: true)]
    #[
        Assert\NotBlank(message: 'you need to choose a pseudo'),
        Assert\Length(
            min: 2,
            max: 50,
            minMessage: 'Minimum {{ limit }} characters',
            maxMessage: 'Maximum {{ limit }} characters'),
    ]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255)]
    #[
        Assert\Length(
            min: 2,
            max: 255,
            minMessage: 'Minimum {{ limit }} characters',
            maxMessage: 'Maximum {{ limit }} characters'),
    ]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    #[
        Assert\Length(
            min: 2,
            max: 255,
            minMessage: 'Minimum {{ limit }} characters',
            maxMessage: 'Maximum {{ limit }} characters'),
    ]
    private ?string $firstname = null;

    #[ORM\Column(length: 13)]
    #[Assert\Regex('/^(?:(?:\+|00)33|0)\s*[1-9](?:[\s.-]*\d{2}){4}$/xs')]
    private ?string $phoneNumber = null;

    #[ORM\Column]
    private ?bool $admin = false;

    #[ORM\Column]
    private ?bool $actif = true;

    #[ORM\ManyToOne(inversedBy: 'students')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Campus $userCampus = null;

    #[ORM\OneToMany(mappedBy: 'leader', targetEntity: Travel::class, orphanRemoval: true)]
    private Collection $leaderTraveler;

    #[ORM\ManyToMany(targetEntity: Travel::class, inversedBy: 'subscriptionedTravelers')]
    private Collection $subscriptionedTravels;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatarFilesname = null;


    public function __construct()
    {
        $this->leaderTraveler = new ArrayCollection();
        $this->subscriptionedTravels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->id;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;


        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function isAdmin(): ?bool
    {
        return $this->admin;
    }

    public function setAdmin(bool $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getUserCampus(): ?Campus
    {
        return $this->userCampus;
    }

    public function setUserCampus(?Campus $userCampus): self
    {
        $this->userCampus = $userCampus;

        return $this;
    }

    /**
     * @return Collection<int, Travel>
     */
    public function getLeaderTraveler(): Collection
    {
        return $this->leaderTraveler;
    }

    public function addLeaderTraveler(Travel $leaderTraveler): self
    {
        if (!$this->leaderTraveler->contains($leaderTraveler)) {
            $this->leaderTraveler->add($leaderTraveler);
            $leaderTraveler->setLeader($this);
        }

        return $this;
    }

    public function removeLeaderTraveler(Travel $leaderTraveler): self
    {
        if ($this->leaderTraveler->removeElement($leaderTraveler)) {
            // set the owning side to null (unless already changed)
            if ($leaderTraveler->getLeader() === $this) {
                $leaderTraveler->setLeader(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Travel>
     */
    public function getSubscriptionedTravels(): Collection
    {
        return $this->subscriptionedTravels;
    }

    public function addSubscriptionedTravel(Travel $subscriptionedTravel): self
    {
        if (!$this->subscriptionedTravels->contains($subscriptionedTravel)) {
            $this->subscriptionedTravels->add($subscriptionedTravel);
        }

        return $this;
    }

    public function removeSubscriptionedTravel(Travel $subscriptionedTravel): self
    {
        $this->subscriptionedTravels->removeElement($subscriptionedTravel);

        return $this;
    }

    public function getAvatarFilename(): ?string
    {
        return $this->avatarFilesname;
    }

    public function setAvatar(?string $newAvatarFilename): self
    {
        $this->avatarFilesname = $newAvatarFilename;

        return $this;
    }


}

src/Form/UserType.php
<?php

    namespace App\Form;

    use App\Entity\Campus;
    use App\Entity\User;
    use Symfony\Bridge\Doctrine\Form\Type\EntityType;
    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\Extension\Core\Type\FileType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Symfony\Component\OptionsResolver\OptionsResolver;

    class UserType extends AbstractType
    {
        public function buildForm(FormBuilderInterface $builder, array $options): void
        {
            $builder
                ->add('email')
                ->add('pseudo')
                ->add('lastname')
                ->add('firstname')
                ->add('phoneNumber')
                ->add('userCampus', EntityType::class, [
                        'class' => Campus::class,
                        'choice_label' => 'name',
                        // 'disabled' => true
                    ]
                )
                ->add('avatar', FileType::class, [
                    'mapped' => false,
                    'label' => 'if you want to have some avatar :',
                    'required' => false
                ]);
        }

        public function configureOptions(OptionsResolver $resolver): void
        {
            $resolver->setDefaults([
                'data_class' => User::class,
            ]);
        }
    }

src/Controller/UserController.php
<?php

    namespace App\Controller;

    use App\Entity\User;
    use App\Form\UserType;
    use App\Repository\UserRepository;
    use App\Service\UserService;
    use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
    use Symfony\Component\HttpFoundation\Request;
    use Symfony\Component\HttpFoundation\Response;
    use Symfony\Component\Routing\Annotation\Route;


    #[Route('/user')]
    class UserController extends AbstractController
    {
        #[Route('/', name: 'app_user_index', methods: ['GET'])]
        public function index(UserRepository $userRepository): Response
        {
            return $this->render('user/index.html.twig', [
                'users' => $userRepository->findAll(),
            ]);
        }

        #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
        public function show(int $id, UserRepository $userRepository): Response
        {
            $user = $userRepository->find($id);
            return $this->render('user/show.html.twig', [
                'user' => $user,
            ]);
        }

        #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
        public function edit(Request $request, User $user, UserRepository $userRepository, $id, UserService $userService): Response
        {


            $form = $this->createForm(UserType::class, $user);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {


                $directory = $this->getParameter('avatar_directory');
                $user = $userService->updateAvatarFile($form, $user, $directory);


                $userRepository->save($user, true);


                return $this->redirectToRoute('app_user_show', ['id' => $id], Response::HTTP_SEE_OTHER);
            }


            return $this->render('user/edit.html.twig', [
                'user' => $user,
                'form' => $form->createView(),
            ]);
        }


        #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
        public function delete(Request $request, User $user, UserRepository $userRepository): Response
        {
            if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
                $userRepository->remove($user, true);
            }

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }


    }

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
            {{ form_widget(form) }}
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <section>
        <h1 class="text-center">Modification</h1>
        <div class="card-body px-4 py-5 px-md-5">
            <div class="row">
                <div class="mx-auto col-10 col-md-8 col-lg-6">
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
                    {{ form_end(form) }}
                </div>
            </div>
            {% if  is_granted("ROLE_ADMIN") %}
                <a href="{{ path('app_user_index') }}">back to list</a>
            {% endif %}
            {% if app.user.id == user.id %}
                <a href="{{ path('app_forgot_password_request') }}"> forgot your password ? </a>
            {% endif %}
        </div>
    </section>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index {% endblock %}

{% block body %}
    <section>
        <h1 class="text-center">List User</h1>
        <div class="container py-5">
            <div class="row">
                {% for user in users %}
                    <div class="col-lg-4">
                        <div class="card mb-4 border-white">
                            <div class="card-body text-center" style="height: 500px">
                                {% if user.avatarFilename %}
                                    <img
                                            src="{{ asset('img/userAvatar/'~ user.avatarFilename ) }}"
                                            alt="avatar" class="rounded-circle img-fluid"
                                            style="width: 150px; min-height: 150px"/>
                                {% else %}
                                    <img
                                            src="{{ asset('img/userAvatar/defaultAvatar.jpg') }}"
                                            alt="avatar" class="rounded-circle img-fluid"
                                            style="width: 150px;height: 150px"/>
                                {% endif %}
                                <h5 class="my-3">{{ user.pseudo }}</h5>
                                <p class="text-muted mb-1">lastname : {{ user.lastname }} </p>
                                <p class="text-muted mb-1">Firstname: {{ user.firstname }} </p>
                                <p class="text-muted mb-1">Email : {{ user.email }}</p>
                                <p class="text-muted mb-4">Campus : {{ user.userCampus.name }}</p>
                                <p class="text-muted mb-4">Role
                                    : {{ user.roles |json_encode(constant('JSON_PRETTY_PRINT')) |raw }}</p>
                                <p class="text-muted mb-1">
                                <div class="d-flex justify-content-center mb-2">
                                    <a class="btn btn-info m-2 my-sm-2 " href="{{ path('app_user_show', {'id': user.id}) }}">show</a>
                                    <a class="btn btn-info m-2 my-sm-2 " href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
                                </div>
                                </p>
                                </div>
                        </div>
                    </div>
                {% else %}
                    <tr>
                        <td colspan="11">no records found</td>
                    </tr>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <section>
        <h1>Create new User</h1>
        {{ include('user/_form.html.twig') }}
        <a href="{{ path('app_user_index') }}">back to list</a>
    </section>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <section>
        <br>
        <h1 class="text-center "> Profile of {{ user.pseudo }}</h1>
        <div class="container py-5">
            <div class="row ">
                <div class="col-lg-4 ">
                    <div class="card mb-4 border-dark" style="height: 345px">
                        <div class="card-body text-center ">
                            {% if user.avatarFilename %}
                                <img
                                        src="{{ asset('img/userAvatar/'~ user.avatarFilename ) }}"
                                        alt="avatar" class="rounded-circle img-fluid"
                                        style="width: 150px; height: 150px"/>
                            {% else %}
                                <img
                                        src="{{ asset('img/userAvatar/defaultAvatar.jpg') }}"
                                        alt="avatar" class="rounded-circle img-fluid"
                                        style="width: 150px; height: 150px;">
                            {% endif %}
                            <h5 class="my-3">{{ user.pseudo }}</h5>
                            <p class="text-muted mb-1">{{ user.lastname }} {{ user.firstname }}</p>
                            {% if is_granted("ROLE_ADMIN") %}
                                <div class="d-flex justify-content-center mb-2"><a
                                            href="{{ path('app_admin_dashboard') }}">back
                                        to Admin list</a>
                                </div>
                            {% endif %}

                            {% if app.user.id == user.id or is_granted("ROLE_ADMIN") %}
                                <div class="d-flex justify-content-center mb-2"><a
                                            href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
                                </div>
                            {% endif %}

                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card mb-4 border-dark " style="height: 345px">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Firstname :</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ user.firstname }}</p>
                                </div>
                            </div>
                            <hr/>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Lastname :</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ user.lastname }}</p>
                                </div>
                            </div>
                            <hr/>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Phone :</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ user.phoneNumber }}</p>
                                </div>
                            </div>
                            <hr/>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Email :</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ user.email }}</p>
                                </div>
                            </div>
                            <hr/>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Campus :</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ user.userCampus.name }}</p>
                                </div>
                            </div>
                            <hr/>
                            {% if is_granted("ROLE_ADMIN") %}
                                <div class="row">
                                    <div class="col-sm-3">
                                        <p class="mb-0">Roles :</p>
                                    </div>
                                    <div class="col-sm-9">
                                        <p class="text-muted mb-0">{{ user.roles |json_encode(constant('JSON_PRETTY_PRINT')) |raw }}</p>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}